#!/bin/bash
# Generates BuildTimestamp.h with current build time

PROJECT_ROOT="$1"

# Exit gracefully if no project root
[ -z "$PROJECT_ROOT" ] && exit 0

HEADER_FILE="$PROJECT_ROOT/plugin/Source/BuildTimestamp.h"

# Only update if directory exists
[ -d "$PROJECT_ROOT/plugin/Source" ] || exit 0

cat > "$HEADER_FILE" << 'EOF'
#pragma once
// Auto-generated by update_timestamp.sh - do not edit manually
EOF

echo "#define BUILD_TIMESTAMP \"$(date '+%Y-%m-%d %H:%M:%S')\"" >> "$HEADER_FILE"

exit 0
